common:
 release_version: 2.0.1
 release_name: 'Brave New World'
 vc_type: 'svn'
 vc_uri: 'http://prsvn.ongame.com/svn/repos'
 vc_dir: '/opt/brazil/current/tmp/svn_tmp'
 vc_read_user: ''
 vc_read_password: ''
 serenity_url: http://serenity.vte.b2c
 serenity_clean_action: /api/clean
 admins: fredrikr
 ad_domain: ongame
 ad_host: ad.ongame.com
 ad_port: 389
 svn_bin: '/usr/bin/svn'
 commit_message_append: 'CR-IGNORE CI-IGNORE'

production:

development:

test:

