common:
 release_version: 1.4
 release_name: 'Serenity'
 vc_type: 'svn'
 vc_uri: 'http://prsvn.ongame.com/svn/repos'
 vc_dir: '/home/rinman/workspace/brazil-git/brazil/tmp/svn_tmp'
 vc_read_user: ''
 vc_read_password: ''
 serenity_url: http://serenity.vte.b2c
 serenity_clean_action: /api/clean
 sql_dir: '/home/rinman/workspace/brazil-git/brazil/tmp/sql'

production:

development:

test:

